include_recipe "helper::package_update"

package "libevent-dev"
package "openssl"
package "libssl-dev"
package "libcurl4-openssl-dev"
package "libtidy-dev"
package "libmcrypt-dev"
package "libxslt1-dev"
package "build-essential"
package "libxml2-dev"
package "libbz2-dev"
package "bison"
package "re2c"
package "libtool"
package "help2man"
package "autoconf"
package "automake"

include_recipe "libjpeg::install"
package "libpng12-dev"
